### ISSUE TITLE
Deny access to home network hosts

### ISSUE THREAD

**Issue by amuuza** [libremesh/network-profiles#24]
As explained in the mailing list [0], some people willing to share their Internet connection don't join community networks when they know hosts in the community will be able to access hosts in their private home network.

I would like to have a network profile where hosts in the community network cannot access hosts of a home network that is sharing its Internet connection.

I understand this may be considered an anti-feature request because I'm actually asking to deny some connections. But, we need it in our poor community because:

- It'd let the whole community use the Internet connections of those who do not feel comfortable by exposing their home network.
- It'd let those mistrustful/unskilled/paranoid/security-conscious people become community members!

For the time being our community network address is just a subrange of the 10.0.0.0/8 network. We plan to communicate in the future with other subranges of the 10.0.0.0/8 network too.
So, I would be happy if I could  have a network profile:
- Allowing access to public addresses and to 10.0.0.0/8
- Denying access to any host within 192.168.0.0/16 and 172.16.0.0/12 private networks
- Using all shared Internet gateways, including those within networks 192.168.0.0/16 and 172.16.0.0/12

But I do not know how to configure it. Do I have to configure /etc/firewall.user? Any tip is welcome.

@ilario also suggested some things in the list [1] I did not understand.

[0] https://lists.libremesh.org/pipermail/lime-users/2017-November/001011.html
[1] https://lists.libremesh.org/pipermail/lime-users/2017-November/001013.html

**Comment by aparcar** [comment]
Do you want to disallow outgoing connections? I'd implement a nat like behaviour to avoid accidentally using the neighbours network printer. 

I'd implement this feature once we decided on a proper solution.

@dangowrt ideas?

**Comment by amuuza** [comment]
Thank you very much aparcar!
But I don't understand your question.
What I want to do is to deny traffic from community hosts (clients of the Libremesh network) to private home network hosts.
Maybe we can chat on IRC/Matrix if I see you there.

**Comment by ilario** [comment]
If I may I will share an example of such situation:
a public environmental analysis agency wants to use a LibreMesh based mesh network for recollecting pollution sensor data, they don't mind to have the rest of the community network to use their nodes as long as this is reciprocal. Moreover they are ok with the community accessing directly the sensors for accessing raw data. They need to access the sensors from their internal network. What they do mind is that their internal network (not the sensors, but printers, network drives etc) must not to be accessible from the rest of the community.

**Comment by nicopace** [comment]
@amuuza Instead of fragmenting the network, it would be wise to properly configure al the hosts around so they don't need to be separated from the whole network and loose all the benefits of having all their devices accesible in the network they use daily.

I would suggest that from LibreMesh we could aid the users to properly configure their unsafe network devices by detecting and notifying them of such conditions.

This could Also happen with NAS, VNC servers, music sharing, our any other service that is not properly configured and that in a Nat was not an but it ends up being in a mesh.

Also, @ilario what they seem to need is not a stereotipical user for us. I guess LibreMesh can be adapted to fit many scenarios, but i'm sure that there are many solutions for networks of sensors. I guess they could do a vpn for the sensors if they want to tinker with the firmware, but I don't see the point of investing design effort on such escenary. If you disagree... could you share a little bit more of why you would, cause I might not be the only that things this way and could help us understand the case :)

**Comment by ilario** [comment]
@nicopace right, I did not explain well enough, rephrasing above.

**Comment by nicopace** [comment]
The case of users having public devices in an open network is a new case that will worry not only to mesh networks, but to networking in general, more if ipv6 comes closer and closer.

I feel that users need to get wiser, devices more aware of this situation, and we could help on that process.

Devices are easy to spot on from LibreMesh cause they have MACs and hostnames that are easy to spot.
The shortest and easiest way to deal with this would be to inform the user of such devices, and let them know that they need to configure them to behave in such a network.

The other simple solution would be to put them behind a nat, outside of the scope of the mesh (a wireless hotspot within the house or office that includes them and hides them behind the nat).

I would suggest that for this overlaping responsabilities a good approach would be to separate them in different devices, or to inform of the situation.

How do u feel about this @amuuza ?

**Comment by brunovianna** [comment]
> The other simple solution would be to put them behind a nat, outside of
> the scope of the mesh (a wireless hotspot within the house or office that
> includes them and hides them behind the nat).
>


This sounds to me by far the easiest solution. All home routers are
preconfigured this way - just plug their wan into a lime node and you have
a protected separate network. The disadvantage is  losing some services
from the mesh.



-- 

bruno@pobox.com ▀─█▄██▄▀▄
http://brunovianna.net ─█▄██▄▀█▀█▄
skype: randomico▀─█▄██▄▀█▀█▄▌██─█▌█▌

**Comment by aparcar** [comment]
> This sounds to me by far the easiest solution. All home routers are
> preconfigured this way - just plug their wan into a lime node and you have
> a protected separate network. The disadvantage is  losing some services
> from the mesh.

You basically need the double amount of devices but it solves the case for home users - being part of the mesh and it's services plus offerings a transport network without exposing private device to everyone. 

@rogerpueyo you added the option of having a NAT from within the qMp node, how hard is it to implement that? 
@libremesh/collaborators are you willing to merge that feature if I create a PR? This could also be expanded with a simple "allow port 22 for mac/ip XY" configuration.

**Comment by G10h4ck** [comment]
I will NOT merge any PR in the direction of making easy to break all direct connections by default, if some device need protection then a specific rule for that device should be made, not the opposite (aka isolate everyone for the sake of a bad configured/unprotected device).

LibreMesh is an attempt to fix the Internet not to reproduce the shitty centralizing decisions that is ruining the current internet.

**Comment by aparcar** [comment]
@nicopace 

> I would suggest that from LibreMesh we could aid the users to properly configure their unsafe network devices by detecting and notifying them of such conditions.

Detecting broken devices like a [CERT](https://www.bsi.bund.de/EN/Topics/IT-Crisis-Management/CERT-Bund/cert-bund_node.html) does sounds fun but also like a lot of work. How would you contact members of the mesh? There is no generic contact approach, is there?

Fixing broken IOT may exceed (my) scope of a mesh devs?

**Comment by nicopace** [comment]
> Detecting broken devices like a CERT does sounds fun but also like a lot of work.

I guess the easiest thing to do is to do a port scan like this: https://www.cyberciti.biz/faq/linux-port-scanning/

And if we find any port that we might recognize as a potential issue (like printers, samba shares, tvs or similar) inform the user.

Another way of detection could be by using the MAC address or the hostname.

> How would you contact members of the mesh?
> There is no generic contact approach, is there?

There are plans to create a way for the node to talk to his owner, but it is a little down the road (unless u want to work on it... in that case, let's chat :) ).

**Comment by nicopace** [comment]
> I will NOT merge any PR in the direction of making easy to break all direct connections by default, if some device need protection then a specific rule for that device should be made, not the opposite (aka isolate everyone for the sake of a bad configured/unprotected device).
> LibreMesh is an attempt to fix the Internet not to reproduce the shitty centralizing decisions that is ruining the current internet.

I agree with @G10h4ck that this issue shouldn't be solved by adding restrictions that add more burden to the already overloaded routers.

And also agree with @amuuza that this is a common scenario that we need to talk about... if I do a scan on our network (QuintanaLibre) I can see lots of devices connected that might not be configured properly, and that NAT has made the users (and device manufacturers) unaware of the risks of a connected device.

I think our role in this path is to discuss how to better aid our users on the proper way of doing it (for me would be to secure them using strong passwords for example), and through that we will have more informed users that will be able next time to know about this (a little more).

**Comment by amuuza** [comment]
>     This sounds to me by far the easiest solution. All home routers are
>     preconfigured this way - just plug their wan into a lime node and
>     you have
>     a protected separate network. The disadvantage is losing some services
>     from the mesh.
>
> You basically need the double amount of devices but it solves the case
> for home users - being part of the mesh and it's services plus
> offerings a transport network without exposing private device to everyone.
>
>

Didn't think of @nicopace 's solution. But aparcar is right, I would need
more devices (because their home routers will probably be modems too).
And I would also need to configure their new access points and disable
the access point of their original home router too.
And they would be surfing the Internet through triple NAT (or quadruple
if their ISP does Carrier-grade NAT, as mine does).

**Comment by nicopace** [comment]
@amuuza I'm sorry to say that I don't know where are you from and which one is your Community Network.
It sounds like the setup you have is more of a managed ISP network than of a Community-led Network... can you specify?

For those that have a network-enabled printer, I'm sure they also have a Wireless AP that they can use as NAT.

The solution that @aparcar was proposing also requires NATing... this one separates it in a different device, and does not require for LibreMesh to include an (still) odd usecase... I'm sure you will be able to describe it more so all can understand it better otherwise :)

**Comment by dangowrt** [comment]
Setting an option for the 'lan' protocol handler to setup firewalling could be implemented in such a way that forwarding incoming connections from mesh to lan is only allowed for RELATED,ESTABLISHED as well as UDP 50000 – 65000 for RTP and P2P stuff on both IPv4 and IPv6. Especially if we are about to delegate public v6 prefixes via gateway tunnels and those are then advertised on the lan this is more or less what users and most (commercial) devices expect (rather than beeing fully exposed to the public arpanet)

**Comment by G10h4ck** [comment]
@dangowrt that break direct connections again except for 50000 - 65000 UDP ports and would be more or less as damaging as a NAT (and still we are not considering the load of connection tracking on the router needed for that kind of things...), what if the people have nextcloud installed? they need to forward ports and the blaahh shit that we have to do on the commercial internet on the community network too?

I agree we need to talk about this thing, but I repeat the ~easy~ militaristic let's close everything by default and similar ~solutions~ will not be merged.

**Comment by dangowrt** [comment]
@G10h4ck nobody ever mentioned that this should be enabled by default. however, i see people here asking for such a feature of the firmware which they would otherwise compensate by introducing another device and another NAT to their network. decent and sensible filters between WAN and LAN do make sense and are much better than (double-)NAT for those who need a more isolated environment...

**Comment by aparcar** [comment]
We could introduce a lime-defaults option `isolate_network` (ofc opt-in) to enable the firewall rules mentioned by @dangowrt.

@G10h4ck please don't get my idea wrong, I just try to add options to LiMe to open the framework to more people with different use cases...

> The solution that @aparcar was proposing also requires NATing... this one separates it in a different device, and does not require for LibreMesh to include an (still) odd usecase... I'm sure you will be able to describe it more so all can understand it better otherwise :)

The use case is that I'm in a house with, say 10 different parties. Everyone like the idea of sharing the internet connection instead of paying 20-40€ monthly. They don't like the idea of learn about cupsd authentication nor want others to use their printers. A (for me) convincing solution is to distribute uplink with LiMe/bmx7 but keep their APs separated - at least if they want to.

**Comment by amuuza** [comment]
On Thursday evening we had another case of another person willing to share their Internet connection, but again only if community hosts were not able to reach their home network. Further talk did not work.

I understand Gio's approach as the cornerstone of the project, but reality sometimes is hard. In the district I live, there are many people suffering poverty. We could provide Internet access for free, many of them would love it, specially migrants. But we do not have enough capacity, we need people sharing their Internet connection. There are some willing to share, but they step back as soon as they know community hosts could connect to their home hosts, and they do not want to talk much more.

I think of it and see again these never-deployed routers I have here, and I want to keep trying to get this network-profile done. 

I have been reading messages again, have understood more things than before (thank you all!), but not all, and I still do not know which files I should play with. Should it be enough by configuring /etc/firewall.user ? I am not a coder, so I would appreciate if anyone could tell me a bit more in detail how to do it so that I could understand and tinker by myself. I also would like to understand possible drawbacks.

We recently discovered https://www.sbmesh.net/ which is a LibreMesh firmware doing what I am looking for (apparently it also restricts traffic from the LAN to the Mesh). I think it uses a solution similar to what @dangowrt suggested, but editing some files I did not expect. We tested it, it did not work, it allowed every communication. I opened an issue to ask @raylas why [0].

[0] https://github.com/sbmesh/sbmesh-profiles/issues/1

**Comment by dangowrt** [comment]
`firewall.user` is ok for adding some work-arounds. Here, however, we are facing a structural problem: We put all interfaces into the same firewall zone.
The true cause for this is that we have just migrated back to use OpenWrt's stock firewall (instead of a bunch of libremesh-specific iptables scripts). The next step now could (and imho should be) to have different firewall zones for mesh, lan and wan. Forwarding rules between zones could then quite easily end up:
 lan -> wan
 lan -> mesh
 mesh -> wan if users sets a tick at 'share my local internet connection with other people in the mesh'

**Comment by aparcar** [comment]
@dangowrt 
not do forget a mesh -> lan right? Unless the user explicitly doesn't want to share it?

**Comment by amuuza** [comment]
Adding these two simple lines to /etc/firewall.user seems to do the job.

iptables -I FORWARD -d 192.168.0.0/16 -j DROP
iptables -I FORWARD -d 172.16.0.0/12 -j DROP

It seems to good to be true.

Am I missing anything?

I mean discussions got complicated (NATing and other stuff) so I might be missing something here.

Does anyone see any connectivity issue -or any other problem- in a community network whose routers have those two lines at /etc/firewall.user ?

(For the time being let's consider home network addresses are not within 10.0.0.0/8, that's for the community)

**Comment by dangowrt** [comment]
If all your home networks are within IPv4 RFC1918 ranges which are not overlapping with addresses used inside the mesh, then this works (though adding those rules to /etc/config/firewall would be much more elegant than using /etc/firewall.user which is kinda ugly and also requires ip*tables to be installed).

Also note that this setup still looks like you'd end up with IPv4 double NAT and hence without any way for UDP-based services (such as VoIP or P2P applications) to work properly, assuming that you also don't have global IPv6 connectivity -- I call that a 'web-surfing connection' rather than 'internet connection' because you are then effectively limited to outgoing TCP traffic (which is sad and prevents next generation distributed technologies we urgently need from working properly).
For that reason I'd suggest to use the LiMe gateway router as the **main** router which would be assigned a public IPv4 address and ideally even a large enough IPv6 prefix by the upstream ISP. DMZ may also be an option, but I never tried.

**Comment by dangowrt** [comment]
@aparcar true. you'd need that rule as well, whether it should be opt-in or opt-out could be a lengthy debate though...

**Comment by nicopace** [comment]
Instead of fragmenting the network, it would be Wise to properly configure al the hosts around so they don't need to be separated from the whole network.
I  would suggest that from libremesh we could aid the users to properly configure their unsafe network devices by detecting and notifying them of such conditions.
This could Also happen with NAS, VNC servers, music sharing, our any other service that is not properly configured and that in a Nat was not an but it ends up being in a mesh

On March 12, 2018 6:15:44 AM EDT, amuza <notifications@github.com> wrote:
>Thank you very much aparcar!
>But I don't understand your question.
>What I want to do is to deny traffic from community hosts (clients of
>the Libremesh network) to private home network hosts.
>Maybe we can chat on IRC/Matrix if I see you there.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/libremesh/network-profiles/issues/24#issuecomment-372258322

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by amuuza** [comment]
I guess this issue can be closed.
